name: Verticular.AllDotNet.CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build_pack_and_publish:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core (3.1)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Setup .NET Core (2.2)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.805

    - name: Setup .NET Full Framework
      uses: warrenbuckley/Setup-MSBuild@v1

    - id: bootstrap
      name: Bootstrap variables
      shell: pwsh
      run: |
        $gb = "${{ github.ref }}".Replace("refs/heads/", "");
        $b = [int]${{ github.run_number }};
        $bn = [datetime]::Now.Date.ToString("yyyyMMdd") + [string]::Format("{0:000}", $b);
        Write-Host "::set-output name=commit::${{ github.sha }}"
        Write-Host "::set-output name=branchName::$gb"
        Write-Host "::set-output name=buildNumber::$bn"

    - name: Show variables
      shell: pwsh
      run: |
        Write-Host "Commit: ${{ steps.bootstrap.outputs.commit }}"
        Write-Host "Branch: ${{ steps.bootstrap.outputs.branchName }}"
        Write-Host "Build: ${{ steps.bootstrap.outputs.buildNumber }}"
      
    - name: Install dependencies
      shell: pwsh
      run: dotnet restore --packages "${{ github.workspace }}/packages" --verbosity minimal --no-cache --ignore-failed-sources
      env: 
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
   
    - name: Build (bin)
      run: dotnet build --configuration CI --no-restore --verbosity minimal --no-incremental -p:GitRevisionNumber="${{ steps.bootstrap.outputs.commit }}" -p:GitBranchName="${{ steps.bootstrap.outputs.branchName }}" -p:BuildNumber="${{ steps.bootstrap.outputs.buildNumber }}" -p:CIBuilder="VSTS" -p:AppendRuntimeToOutputPath=true --runtime win
    
    - name: Build (for pack)
      run: dotnet build --configuration CI --no-restore --verbosity minimal --no-incremental -p:GitRevisionNumber="${{ steps.bootstrap.outputs.commit }}" -p:GitBranchName="${{ steps.bootstrap.outputs.branchName }}" -p:BuildNumber="${{ steps.bootstrap.outputs.buildNumber }}" -p:CIBuilder="VSTS" -p:AppendRuntimeToOutputPath=false --runtime win
    
    - name: Test
      run: dotnet test --configuration CI --no-restore --no-build --verbosity normal --logger trx --collect "Code Coverage" --results-directory "${{ github.workspace }}/TestResults" --runtime win

    - name: Pack nuget packages
      run: dotnet pack --configuration CI --no-build --verbosity minimal --serviceable --output "${{ github.workspace }}/nuget" -p:GitRevisionNumber="${{ steps.bootstrap.outputs.commit }}" -p:GitBranchName="${{ steps.bootstrap.outputs.branchName }}" -p:BuildNumber="${{ steps.bootstrap.outputs.buildNumber }}" -p:CIBuilder="VSTS" -p:AppendRuntimeToOutputPath=false --runtime win

    #- name: Push generated package to GitHub registry
    #  run: dotnet nuget push **/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/mhudasch/index.json --api-key ${{ secrets.GITHUB_TOKEN }}

    - name: Push generated package to GitHub registry
      run: dotnet nuget push **/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_ORG_TOKEN }}

    - name: Upload nuget artifact
      uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: ${{ github.workspace }}/nuget/*.nupkg

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: ${{ github.workspace }}/TestResults/

  sonar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Setup .NET Core (3.1)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - id: bootstrap
      name: Bootstrap variables
      shell: pwsh
      run: |
        $gb = "${{ github.ref }}".Replace("refs/heads/", "");
        $b = [int]${{ github.run_number }};
        $bn = [datetime]::Now.Date.ToString("yyyyMMdd") + [string]::Format("{0:000}", $b);
        Write-Host "::set-output name=commit::${{ github.sha }}"
        Write-Host "::set-output name=branchName::$gb"
        Write-Host "::set-output name=buildNumber::$bn"

    - name: Show variables
      shell: pwsh
      run: |
        Write-Host "Commit: ${{ steps.bootstrap.outputs.commit }}"
        Write-Host "Branch: ${{ steps.bootstrap.outputs.branchName }}"
        Write-Host "Build: ${{ steps.bootstrap.outputs.buildNumber }}"

    - name: Sonarscanner for dotnet
      uses: Secbyte/dotnet-sonarscanner@v2.2
      with:
        buildCommand: dotnet build --configuration CI --verbosity minimal --no-incremental -p:GitRevisionNumber="${{ env.GIT_COMMIT }}" -p:GitBranchName="${{ env.GIT_BRANCH }}" -p:BuildNumber="${{ env.BUILD_NR }}" -p:CIBuilder="VSTS" -p:AppendRuntimeToOutputPath=true -p:IncludeFullFramework=false --runtime linux-x64
        testCommand: dotnet test --configuration CI --no-build --verbosity normal --logger trx --collect "Code Coverage" --results-directory "${{ github.workspace }}/TestResults" --runtime linux-x64 -p:IncludeFullFramework=false
        projectKey: mhudasch:verticular.extensions.randomstrings
        projectName: verticular.extensions.randomstrings
        sonarOrganisation: mhudasch-github
        beginArguments: >
            /d:sonar.verbose="true"
            /v:"1.0.0-alpha01"
            /d:sonar.branch.name="${{ steps.bootstrap.outputs.branchName }}"

      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        GIT_COMMIT: ${{ steps.bootstrap.outputs.commit }}
        GIT_BRANCH: ${{ steps.bootstrap.outputs.branchName }}
        BUILD_NR: ${{ steps.bootstrap.outputs.buildNumber }} 

